- repo: local
  hooks:
    - id: uv-pip-compile
      name: Compile requirements.txt
      entry: uv pip compile pyproject.toml -o requirements.txt --no-header --no-annotate --no-deps
      language: system
      pass_filenames: false
