[project]
name = "webdriver-factory"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "selenium>=4.29.0",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pre-commit>=4.1.0",
    "pytest>=8.3.5",
    "ruff>=0.9.9",
]
